# -*- coding: utf-8 -*-
"""textSummarizer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P0ndyMl90Bxk1zp7DyKhXWWzbiHwWNDk
"""

from transformers import pipeline
import streamlit as st

"""## Initiating transformer pipeline to summarize the text

We now try to initiate the pipeline between the BART model and our local system, after which your text will be analysed and then summarised
"""

def summarize(text, min, max, threshold = 4096, curve = 0.1):
  charCount = len(text)

  if charCount > threshold:
    st.write("Hey there! You are exceeding the limit of 4096 characters. Please truncate the text to generate the summary")
    return

  wordCount = text.count(" ")

  min = round(wordCount * curve)
  max = wordCount - min

  print(min)
  print(max)
  summarizer = pipeline("summarization", model="facebook/bart-large-cnn")
  #fil = open("file.txt", "r", encoding="utf-8")

  summarized = summarizer(text, min_length = min, max_length = max, do_sample = False)

  return summarized[0]['summary_text']

if __name__ == "__main__":
  #text = '''If you spend any amount of time on food internet, you've likely been inundated with tinned fish content, whether the “tinned fish date night” videos are dominating your TikTok For You page or your own friend group's dinner parties have been infiltrated by these oily little tins of mackerel and tuna. Tinned fish is officially chic, a fact that seriously blows my mind considering that there are few foods more overrated than (most) fish in a can.
#
  #Sure, like pretty much everyone else in the world, I enjoy a good can of oil-packed tuna stirred together with mayonnaise, capers, and dijon mustard for lunch. I can appreciate the convenience of canned salmon when you're making onigiri at home. Korean canned tuna is spicy and full of flavor, and it's always nice to have a can of clams in the pantry for those times when you want to make an easy, impromptu chowder. But that's standard grocery store stuff, not this new generation of fancy sea creatures, from ink-drenched squid to geoduck, that are being packed into beautifully decorated, ridiculously pricey tins promising a luxury seafood without the prep and the cooking.
#
  #In addition to reminding you of that amazing trip to Lisbon, tinned fish has also become shorthand for being both worldly and having an adventurous palate.
#
  #It doesn't look like that trend is going anywhere soon, either. There are countless cool indie brands, like Fishwife and Scout, along with tinned fish subscription clubs, multiple tinned fish cookbooks, and T-shirts. As Eater NY reported this week, a two-story shop called the Fantastic World of the Portuguese Sardine just opened its doors in Manhattan, selling dozens of different types of oily tinned fish. One of those options is a $44 tin of sardines, which my colleague Robert Sietsema notes were “skinned and deboned laboriously by hand,” with a mild flavor and dots of gold leaf to really drive home the luxury vibe. He “vastly” preferred a $15 tin, and noted that he didn't see much distinction between these extravagant tins and plain ol' supermarket sardines.
#
  #And that's because even the best tinned fish is just okay. Unlike the medium-rare filet of seared salmon you might order at a restaurant, tinned fish and other types of seafood are cooked at high temperatures to ensure that they're shelf-stable. That might be less noticeable in fatty fishes like tuna and salmon, but it lends a distinctly rubbery texture to more delicate shellfish, like mussels and oysters. Meanwhile, fresh sardines may be hard to come by in my part of the world, but when they are in season, there are few things better than cooking them whole in a pan with lemon and herbs.
#
  #And considering the price point of many of these fancy tins, why exactly aren't we just eating more fresh fish? On a recent trip to Whole Foods, I noticed a 3.5 ounce can of smoked salmon (brand name withheld to protect the innocent) with Sichuan chile crisp selling for $14. It's a tinned fish I've tried before, and it's perfectly fine, especially when stirred into a dip with cream cheese, chives, and more chile crisp. But at that same Whole Foods, I could buy an entire pound of Atlantic salmon filets for just $2 more. And if my heart was set on smoked salmon, I could pay $12 for eight ounces of the store's fresh, cold-smoked version.
#
  #On some level, I get it. The idea of having fish that's already cooked, that you don't have to worry about thawing out or making sure it hasn't spoiled in your refrigerator, is pretty appealing. The tins do look nice when arranged on a wooden board with crackers and olives, but when they cost as much as $26 for a single can of tuna, it starts to feel a little bit like a scam. Is this really a luxury ingredient, or does it just look cool on Instagram?
#
  #Over the last couple of years, tinned fish has emerged as a status symbol for the food sophisticate, like funky natural wines or expensive olive oil. But it's just another pantry staple, one that's nice every once in a while, not something that should be a fixture at every single dinner party. If I'm never asked to pay $20 for a plate of cold, canned sardines at a restaurant again, it will be too soon. '''

  text = st.text_area('Enter text to summarize here!')
  st.write('Summary: ', summarize(text, min, max))